package commands

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"

	"filippo.io/age"
	"github.com/spf13/cobra"
	"golang.org/x/term"
)

// P15 — local age keypair generation + decryption helpers for the
// scheduled-backup flow. The server never sees the private half: keygen
// runs entirely client-side, decrypt operates on bytes the operator
// already downloaded.

var (
	backupKeygenOutput      string
	backupKeygenForceStdout bool
	backupDecryptIdentity   string
	backupDecryptInput      string
	backupDecryptOutput     string
	backupDecryptForceStdout bool
)

var backupKeygenCmd = &cobra.Command{
	Use:   "keygen",
	Short: "Generate an age X25519 keypair locally for backup encryption (no server round-trip)",
	Long: `Generate a fresh age X25519 keypair. The secret key is written to the
output file (or stdout with --force-stdout); the corresponding recipient
public key is printed to stderr for easy copy-paste into

  nisctl operator backup add-recipient OPERATOR --pubkey <pubkey>

NIS never sees the secret key — keep it somewhere safe (1Password, yubikey,
encrypted disk). Without it, future scheduled backups encrypted to this
recipient become unrecoverable.

By default the secret-key file is mode 0600. Writing to stdout requires
--force-stdout to avoid accidentally leaking the secret to your shell
scrollback.`,
	RunE: runBackupKeygen,
}

var backupDecryptCmd = &cobra.Command{
	Use:   "decrypt",
	Short: "Decrypt an age-encrypted backup artifact locally",
	Long: `Decrypt an age-encrypted backup artifact using the identity (secret key)
file generated by "nisctl backup keygen". The decrypted YAML is written to
the output file (or stdout with --force-stdout).

Output to stdout requires --force-stdout because the YAML contains the
full operator identity tree including encrypted NKey seeds — leaking it
to shell scrollback defeats the entire backup-at-rest threat model.

The decrypted bytes can be piped to "nisctl restore" (or used as the -f
input).`,
	RunE: runBackupDecrypt,
}

func init() {
	backupCmd.AddCommand(backupKeygenCmd)
	backupCmd.AddCommand(backupDecryptCmd)

	backupKeygenCmd.Flags().StringVarP(&backupKeygenOutput, "output", "o", "", "output file for the secret key (default: required unless --force-stdout)")
	backupKeygenCmd.Flags().BoolVar(&backupKeygenForceStdout, "force-stdout", false, "DANGER: emit secret key to stdout (shoulder-surf risk)")

	backupDecryptCmd.Flags().StringVarP(&backupDecryptIdentity, "identity", "i", "", "path to age identity file (secret key) — required")
	backupDecryptCmd.Flags().StringVarP(&backupDecryptInput, "in", "f", "", "input file (age-encrypted) — required")
	backupDecryptCmd.Flags().StringVarP(&backupDecryptOutput, "output", "o", "", "output file for plaintext YAML (default: required unless --force-stdout)")
	backupDecryptCmd.Flags().BoolVar(&backupDecryptForceStdout, "force-stdout", false, "DANGER: emit plaintext YAML to stdout (shoulder-surf risk; YAML contains encrypted seeds)")
	_ = backupDecryptCmd.MarkFlagRequired("identity")
	_ = backupDecryptCmd.MarkFlagRequired("in")
}

func runBackupKeygen(cmd *cobra.Command, _ []string) error {
	if backupKeygenOutput == "" && !backupKeygenForceStdout {
		return fmt.Errorf("provide -o/--output FILE, or pass --force-stdout to accept the shoulder-surf risk")
	}
	if backupKeygenOutput != "" && backupKeygenForceStdout {
		return fmt.Errorf("--output and --force-stdout are mutually exclusive")
	}

	id, err := age.GenerateX25519Identity()
	if err != nil {
		return fmt.Errorf("generate identity: %w", err)
	}
	pubkey := id.Recipient().String()
	secret := id.String()

	out := []byte(fmt.Sprintf("# created by `nisctl backup keygen`\n# public key: %s\n%s\n", pubkey, secret))

	if backupKeygenForceStdout {
		// Belt-and-suspenders: refuse stdout-to-TTY even with --force-stdout
		// unless explicitly piped. Operators who really want to copy from a
		// terminal still can — they redirect to a file or pipe.
		if term.IsTerminal(int(os.Stdout.Fd())) {
			return fmt.Errorf("stdout is a TTY — refusing to emit secret key to a visible terminal even with --force-stdout. Redirect to a file (>) or pipe (|) instead")
		}
		if _, err := os.Stdout.Write(out); err != nil {
			return fmt.Errorf("write stdout: %w", err)
		}
	} else {
		f, err := os.OpenFile(backupKeygenOutput, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
		if err != nil {
			return fmt.Errorf("open output: %w", err)
		}
		if _, werr := f.Write(out); werr != nil {
			_ = f.Close()
			return fmt.Errorf("write secret key: %w", werr)
		}
		// Explicit close + error — flush failures on a secret-key write
		// must surface, a defer-swallowed error leaves a truncated file
		// that silently fails to parse next time.
		if cerr := f.Close(); cerr != nil {
			return fmt.Errorf("close output: %w", cerr)
		}
	}

	// Pubkey to stderr so the operator sees it even when stdout was
	// redirected to a file. Tagged so a future hook can grep it.
	fmt.Fprintf(os.Stderr, "age public key (recipient): %s\n", pubkey)
	fmt.Fprintln(os.Stderr, "Add it to an operator with:")
	fmt.Fprintf(os.Stderr, "  nisctl operator backup add-recipient OPERATOR --pubkey %s\n", pubkey)
	return nil
}

func runBackupDecrypt(cmd *cobra.Command, _ []string) error {
	if backupDecryptOutput == "" && !backupDecryptForceStdout {
		return fmt.Errorf("provide -o/--output FILE, or pass --force-stdout to accept the shoulder-surf risk")
	}
	if backupDecryptOutput != "" && backupDecryptForceStdout {
		return fmt.Errorf("--output and --force-stdout are mutually exclusive")
	}

	identities, err := loadAgeIdentities(backupDecryptIdentity)
	if err != nil {
		return fmt.Errorf("load identity: %w", err)
	}

	in, err := os.Open(backupDecryptInput)
	if err != nil {
		return fmt.Errorf("open input: %w", err)
	}
	defer func() { _ = in.Close() }()

	r, err := age.Decrypt(in, identities...)
	if err != nil {
		return fmt.Errorf("age decrypt: %w", err)
	}

	if backupDecryptForceStdout {
		if term.IsTerminal(int(os.Stdout.Fd())) {
			return fmt.Errorf("stdout is a TTY — refusing to emit plaintext (contains encrypted NKey seeds) to a visible terminal. Redirect to a file (>) or pipe (|) instead")
		}
		if _, err := io.Copy(os.Stdout, r); err != nil {
			return fmt.Errorf("decrypt stream: %w", err)
		}
	} else {
		f, err := os.OpenFile(backupDecryptOutput, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
		if err != nil {
			return fmt.Errorf("open output: %w", err)
		}
		if _, werr := io.Copy(f, r); werr != nil {
			_ = f.Close()
			return fmt.Errorf("decrypt to file: %w", werr)
		}
		// Explicit close + error — same rationale as keygen: a truncated
		// plaintext file silently produces a corrupt YAML that the next
		// restore step rejects with a less-helpful error.
		if cerr := f.Close(); cerr != nil {
			return fmt.Errorf("close output: %w", cerr)
		}
		fmt.Fprintf(os.Stderr, "Decrypted to %s\n", backupDecryptOutput)
	}
	return nil
}

// loadAgeIdentities reads an age identity file (one secret key per line,
// `#`-comments tolerated) and returns the parsed X25519 identities. Anything
// that isn't a recognised AGE-SECRET-KEY-1... line is rejected so the
// operator doesn't silently pass in a pubkey file by mistake.
func loadAgeIdentities(path string) ([]age.Identity, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	ids, err := age.ParseIdentities(bytes.NewReader(data))
	if err != nil {
		return nil, fmt.Errorf("parse identities: %w", err)
	}
	if len(ids) == 0 {
		return nil, errors.New("no identities found in file")
	}
	return ids, nil
}
